apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  dbaeflask
  namespace: majindean 
  labels: 
    app:  dbaeflask
spec: 
  selector: 
    matchLabels: 
      app: dbaeflask
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  dbaeflask
    spec: 
      containers: 
      - name:  dbaeflask
        image:  majindean/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  dbaeflask
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: dbaeflask
  namespace: majindean 
spec: 
  selector: 
    app: dbaeflask
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: dbaeflask
    protocol: TCP 
    port: 80 
    targetPort: 5000